### ISSUE TITLE
when i run 'npm install screen-recorder' i get some error 

### ISSUE THREAD

**Issue by smallH** [tomashanacek/screen-recorder#1]
hello , thank you for your code, but when i run '$ npm install screen-recorder', i get some error like this:

error LNK2001: 无法解析的外部符号 "public: static void __cdecl ScreenRecorderWrapper::Init(class v8::Local<class v8::Object>)" (?Init@ScreenRecorderWrapp

ect@v8@@@v8@@@Z) [C:\Users\netinnet\node_modules\screen-recorder\build\addon.vcxproj]
innet\node_modules\screen-recorder\build\Release\addon.node : fatal error LNK1120: 1 个无法解析的外部命令 [C:\Users\netinnet\node_modules\screen-recorder

what is wrong ?

**Comment by tomashanacek** [comment]
Hi Windows version isn't currently supported.
